### ISSUE TITLE
iceoryx error: error in sending keep alive.

### ISSUE THREAD

**Issue by SEEKERXC** [dora-rs/dora-drives#29]
**Describe the bug**
Runtime error.

**To Reproduce**
1. Dora start daemon: `dora up` 
2. Start a new dataflow:
              `for  some scenarios:
                      dora-coodination dataflow.yaml`

**Screenshots or Video**
<img width="684" alt="1378DC3B-8FEC-4bc0-AEDA-F39FE32C2B9B" src="https://user-images.githubusercontent.com/28669749/222062184-0e255e61-3436-4183-99f3-6df8f687ff4d.png">

**Environments (please complete the following information):**
ubuntu20.04
dora1.3

**Comment by haixuanTao** [comment]
Thanks for using dora and dora-drives! :smile: 

We are currently working on replacing iceoryx with our own shared memory process. This issue should solve itself in the future dora release.
