### ISSUE TITLE
E: Unable to locate package libcudnn8

### ISSUE THREAD

**Issue by meua** [dora-rs/dora-drives#43]
**Describe the bug**
E: Unable to locate package libcudnn8

**To Reproduce**
Linux | Ubuntu 20.04.5 LTS |  
-- | -- | --
Pytorch | 1.11 | Installation below
NVIDIA Driver | 525.105.17 |  
CUDA | 12.0 |  
dora-rs | 0.2.2 | Installation below

</body>
</html>

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/11570442/230840536-8e7ca996-e9ae-4c9a-90ac-6593042e2c0a.png)

**Comment by haixuanTao** [comment]
This seems to be a cuda installation issue. I would suggest looking at https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html

**Comment by meua** [comment]
fixed the issue:
```
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600

sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub

sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"

sudo apt-get update

sudo apt-get install libcudnn8=8.9.0.*-1+cuda12.1

sudo apt-get install libcudnn8-dev=8.9.0.*-1+cuda12.1
```
