### ISSUE TITLE
The following packages have unmet dependencies：libegl-dev、libgl-dev、libglu1-mesa-dev、libglu-dev、libxext-dev

### ISSUE THREAD

**Issue by meua** [dora-rs/dora-drives#44]
**Describe the bug**

**To Reproduce**
1、in installation.html
2、execute> sudo apt-get install --fix-missing -y libcudnn8 ssh libqt5core5a libeigen3-dev cmake qtbase5-dev libpng16-16 libtiff5 python3-tk libgeos-dev vim build-essential libopenblas-dev libssl-dev

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/11570442/230842431-9a69696d-4b7a-4e34-88d0-77b4002de605.png)

**Environments (please complete the following information):**
 - System info: Linux jia 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Dora version：dora-cli 0.2.2、dora-rs 0.2.2

**Comment by haixuanTao** [comment]
Qtbase5-dev is used for carla. I'm not sure if this dependency is still used. You can either try to remove it or try to check https://howtoinstall.co/en/qtbase5-dev for more. There's little I can do on my end about this.
