### ISSUE TITLE
By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project

### ISSUE THREAD

**Issue by NavyHub** [dora-rs/dora-drives#45]
**Describe the bug**
CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.

**To Reproduce**
1. ./scripts/install.sh

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/40234106/231073076-ed64e99d-214c-4b86-a671-6a18b2754cee.png)

**Environments (please complete the following information):**
 - System info:Linux jia 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Dora version 0.2.2

**Comment by meua** [comment]
to fix>: sudo aptitude install qtbase5-dev

**Comment by NavyHub** [comment]
Thanks
