### ISSUE TITLE
todo：dora-drives supports Chinese documents

### ISSUE THREAD

**Issue by meua** [dora-rs/dora-drives#53]
**Is your feature request related to a problem? Please describe.**
dora-drives currently only has English documents and no Chinese documents yet, so it is not very friendly to mainland China

**Describe the solution you'd like**
The dora-drives document can be switched between Chinese and English

**Describe alternatives you've considered**
dora-drives supports Chinese documents

**Comment by haixuanTao** [comment]
The chinese version of dora and dora-drives is now live: https://dora.carsmos.ai/zh-CN/
