### ISSUE TITLE
Cannot find a compatible Vulkan Driver when using Thunderbolt 3 interface for external graphics card

### ISSUE THREAD

**Issue by PiKaChuZhao** [dora-rs/dora-drives#61]
**Describe the bug**
In the environment where the Thunderbolt 3 interface is connected to an external graphics card, when installing oasis, there will be a problem of Cannot fina a compatible Vulkan Driverd.

**To Reproduce**
1. Prepare the environment: `Ubuntu host with Thunderbolt 3 external graphics card` 
2. Start installation: `./install.sh`
3. Stop dataflow: `Cannot find a compatible Vulkan device or driver.Try updating your video driver to a more recent version and make sure your video card supports Vulkan

**Expected behavior**
1. Add `-vulkan` to the `command:` line of the calar.yaml file
2. Reinstall the graphics card driver: `sudo bash NVIDIA-Linux-*.run –-no-opengl-files –-no-x-check`
3. Redeploy the environment: ./install.sh

**Screenshots or Video**
![image](https://github.com/dora-rs/dora-drives/assets/32784721/e8fcb194-1f7d-479a-8374-eed2485d9e72)

**Environments (please complete the following information):**
 - System info: [Ubuntu18.04]
 - Dora version [dora-cli 0.2.2-rc-2]

**Additional context**
For details, please refer to the link https://github.com/carla-simulator/carla/issues/4687#issuecomment-1153632222

**Comment by haixuanTao** [comment]
Is this related to the Carsmos competititon?

If not you can try to use the docker version of carla:
```bash
docker pull carlasim/carla:0.9.13
docker run --privileged --gpus all --net=host -e DISPLAY=$DISPLAY carlasim/carla:0.9.13 /bin/bash ./CarlaUE4.sh -carla-server -world-port=2000 
```

Also, I have recently updated the getting started guide. You can have a look here: https://dora.carsmos.ai/docs/guides/autonomous-driving/installation

**Comment by meua** [comment]
This problem will be in the carsmos FAQ list shortly, not as a general solution.

**Comment by haixuanTao** [comment]
I'll close this issue in this case.
