### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by laqangela** [dora-rs/dora-drives#63]
**Describe the bug**
I have downloaded the Oasis in Ubuntu 22.04.3 LTS. But every time I start a new project, there are always two failure cases：
Case1——The running status is Abnormal and the task result is Invalid like this：
<img width="1407" alt="截屏2023-11-10 14 04 02" src="https://github.com/dora-rs/dora-drives/assets/107610775/f6a6f5b9-8919-4699-a3de-2434f35c5fec">
And the details is：
<img width="906" alt="截屏2023-11-10 13 53 42" src="https://github.com/dora-rs/dora-drives/assets/107610775/90520e1c-c053-4f5d-a00c-c1a95c429ede">

Then I run “docker logs -f oasis-data” : 
<img width="1451" alt="截屏2023-11-10 13 54 03" src="https://github.com/dora-rs/dora-drives/assets/107610775/9165e2ba-c379-4623-855e-41b86c13bb38">

Case2——The pygame window appears but a popup appears: 
<img width="1313" alt="528d4cff6b3bdd00933ce333a3eed022" src="https://github.com/dora-rs/dora-drives/assets/107610775/2637941b-b350-4329-ad36-e8211b6cca0f">
The log details：
<img width="614" alt="截屏2023-11-10 18 47 15" src="https://github.com/dora-rs/dora-drives/assets/107610775/7a8ab91b-b2c2-4336-8c32-bb0d1531cc08">

To deal with this two problems, I have tried "./uninstall.sh -full" and "./install.sh" and restart my computer many times, but it still doesn't work .

**Expected behavior**
I want to launch a project successfully! 

**Screenshots or Video**

**Environments (please complete the following information):**
 - System info: [use `uname --all` on LInux]
 - Dora version [use `dora --version` and `pip show dora-rs`]
<img width="657" alt="截屏2023-11-10 16 05 53" src="https://github.com/dora-rs/dora-drives/assets/107610775/4b0e2d93-6693-43ce-b05f-ed7a7e66cc4b">

**Comment by haixuanTao** [comment]
Hi, Thanks for participating in the Carla-Oasis competition. 

I will not be able to help you on this as I'm not familiar with Oasis at all. You should probably reach out on WeChat with them.
