### ISSUE TITLE
flake8 5.0.4 requires importlib-metadata<4.3,>=1.1.0; python_version < "3.8", but you have importlib-metadata 6.0.0 which is incompatible.

### ISSUE THREAD

**Issue by caixxuan** [dora-rs/dora-drives#65]
**Describe the bug**
something wrong when "pip install -r install_requirements.txt & pip install -r requirements.txt":
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-api 1.22.0 requires importlib-metadata<7.0,>=6.0, but you have importlib-metadata 4.2.0 which is incompatible.
Successfully installed einops-0.3.2 importlib-metadata-4.2.0
(dora3.7) cai@cai:~/Downloads/dora-drives$ pip install importlib-metadata==6.0.0
Collecting importlib-metadata==6.0.0
  Using cached importlib_metadata-6.0.0-py3-none-any.whl (21 kB)
Requirement already satisfied: zipp>=0.5 in /home/cai/anaconda3/envs/dora3.7/lib/python3.7/site-packages (from importlib-metadata==6.0.0) (3.15.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/cai/anaconda3/envs/dora3.7/lib/python3.7/site-packages (from importlib-metadata==6.0.0) (4.3.0)
Installing collected packages: importlib-metadata
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 4.2.0
    Uninstalling importlib-metadata-4.2.0:
      Successfully uninstalled importlib-metadata-4.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flake8 5.0.4 requires importlib-metadata<4.3,>=1.1.0; python_version < "3.8", but you have importlib-metadata 6.0.0 which is incompatible.
Successfully installed importlib-metadata-6.0.0

**To Reproduce**
1. Dora start daemon: `dora up` 
2. Start a new dataflow: `dora start dataflow.yaml`
3. Stop dataflow: `dora stop`
4. Destroy dataflow: `dora destroy`

**Expected behavior**

**Screenshots or Video**

**Environments (please complete the following information):**
 - System info: [use `uname --all` on Linux]
 - Dora version: [use `dora --version` and `pip show dora-rs`]

**Additional context**

**Comment by haixuanTao** [comment]
Can you try this new branch:
```bash
git checkout fix-opendrive
```

and see if you still have errors?

**Comment by caixxuan** [comment]
for the second error, how to solve this error, I have not changed anything but just follow the guide, this error is related to the first one or the third one?

**Comment by haixuanTao** [comment]
You should try:

```
git checkout fix-opendrive
```

and then run your dataflow.

It's related to the latest version of `dora-rs`

**Comment by haixuanTao** [comment]
Happy if it works for you! I think that if Carla run on your GPU, it’s going to be faster. You should check that Vulkan is well installed on your computer.
