### ISSUE TITLE
dora node packet loss

### ISSUE THREAD

**Issue by RuPingCen** [dora-rs/dora-drives#67]
**Describe the bug**
The dora is  V0.3.2. 

I use two nodes. Node A is written in Python. Node B is written in c/c++.

Node A reads GPS data at a 20ms cycle and sends the data via a json string. Node B performs coordinate conversion by receiving data from node A, **but I found that node B will lose data packets when receiving data from node A.**

Here I print the seq number of the data pub by node A, the message count received by node B, and the time when the message was received. There was no packet loss at the beginning, but after running for a while, the message count received by node B was not equal to the seq value of the message.

And, the period of node B to receive data should normally be 20ms, which depends on the period of node A sending data. However, the following picture shows that the time difference between the two events is 40ms. （lower left corner）

here is the test code:
https://github.com/dora-rs/autoware.universe/blob/feature/autoware_dora/localization/ekf_localizer/test_ekf_dataflow.yml

![2024-05-28 10-57-13 的屏幕截图](https://github.com/dora-rs/dora-drives/assets/18321455/80078083-7196-457a-9374-683bcddb948a)

**Comment by phil-opp** [comment]
(issue reopened in https://github.com/dora-rs/dora/issues/515)
